name: flutter_painter
version: 2.0.1
description: A Flutter widget to draw scribbles, text, shapes and images on a background image or color
homepage: https://github.com/Llamalogic/flutter_painter
repository: https://github.com/LlamaLogic/flutter_painter
issue_tracker: https://github.com/LlamaLogic/flutter_painter/issues
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.15.0

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3

flutter:
